Install-WindowsFeature -Name Web-Server; 
$thislocation = Get-Location;
Copy-Item "${thislocation}\config.yaml" -Destination "${Env:windir}\Temp\config.yaml";
Copy-Item "${thislocation}\salt-content.zip" -Destination "c:\inetpub\wwwroot\salt-content.zip"; 
#Invoke-WebRequest "${WAMCustConfPath}" -OutFile "${Env:windir}\Temp\config.yaml"; 
#Invoke-WebRequest "${WAMCustSaltContentPath}" -OutFile "c:\inetpub\wwwroot\salt-content.zip"; 
Invoke-WebRequest "https://raw.githubusercontent.com/ewierschke/ra/wip/scripts/winwatchwcleanup.ps1" -OutFile "${Env:windir}\Temp\wamscript.ps1";  
Get-Content "${Env:windir}\Temp\wamscript.ps1" | ForEach-Object { $_ -replace "C:\\Program Files\\Python36\\Lib\\site-packages\\watchmaker\\static\\config.yaml","${Env:windir}\Temp\config.yaml" } | Set-Content "${Env:windir}\Temp\winwatchwcleanup.ps1"; 
Invoke-WebRequest "https://raw.githubusercontent.com/ewierschke/ra/wip/scripts/schedulenextscripttrim.ps1" -OutFile "${Env:windir}\Temp\schedulenextscripttrim.ps1";
powershell.exe -ExecutionPolicy Unrestricted -File "${Env:windir}\Temp\schedulenextscripttrim.ps1";
exit 0;